%% Menu
Active = menu('Active Control is On', ...
                'Yes',...
             	'No');
Profile = menu('Road profile', ...
                'Ramp',...
             	'Sinusoid',...
                'Rectified Sinusoid',...
                'Random');
